/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as JourneyIdRouteImport } from './routes/journey.$id'
import { Route as CreateJourneyRouteImport } from './routes/create.journey'
import { Route as JourneyIdIndexRouteImport } from './routes/journey.$id.index'
import { Route as CreateJourneyIndexRouteImport } from './routes/create.journey.index'
import { Route as JourneyIdStoryRouteImport } from './routes/journey.$id.story'
import { Route as JourneyIdSettingsRouteImport } from './routes/journey.$id.settings'
import { Route as JourneyIdPostedRouteImport } from './routes/journey.$id.posted'
import { Route as JourneyIdCompleteRouteImport } from './routes/journey.$id.complete'
import { Route as JourneyIdAddRouteImport } from './routes/journey.$id.add'
import { Route as CreateJourneyFirstPostRouteImport } from './routes/create.journey.first-post'

const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateJourneyRoute = CreateJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => CreateRoute,
} as any)
const JourneyIdIndexRoute = JourneyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyIdRoute,
} as any)
const CreateJourneyIndexRoute = CreateJourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateJourneyRoute,
} as any)
const JourneyIdStoryRoute = JourneyIdStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdSettingsRoute = JourneyIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdPostedRoute = JourneyIdPostedRouteImport.update({
  id: '/posted',
  path: '/posted',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdCompleteRoute = JourneyIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdAddRoute = JourneyIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => JourneyIdRoute,
} as any)
const CreateJourneyFirstPostRoute = CreateJourneyFirstPostRouteImport.update({
  id: '/first-post',
  path: '/first-post',
  getParentRoute: () => CreateJourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/create/journey': typeof CreateJourneyRouteWithChildren
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/create/': typeof CreateIndexRoute
  '/create/journey/first-post': typeof CreateJourneyFirstPostRoute
  '/journey/$id/add': typeof JourneyIdAddRoute
  '/journey/$id/complete': typeof JourneyIdCompleteRoute
  '/journey/$id/posted': typeof JourneyIdPostedRoute
  '/journey/$id/settings': typeof JourneyIdSettingsRoute
  '/journey/$id/story': typeof JourneyIdStoryRoute
  '/create/journey/': typeof CreateJourneyIndexRoute
  '/journey/$id/': typeof JourneyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/create': typeof CreateIndexRoute
  '/create/journey/first-post': typeof CreateJourneyFirstPostRoute
  '/journey/$id/add': typeof JourneyIdAddRoute
  '/journey/$id/complete': typeof JourneyIdCompleteRoute
  '/journey/$id/posted': typeof JourneyIdPostedRoute
  '/journey/$id/settings': typeof JourneyIdSettingsRoute
  '/journey/$id/story': typeof JourneyIdStoryRoute
  '/create/journey': typeof CreateJourneyIndexRoute
  '/journey/$id': typeof JourneyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/create/journey': typeof CreateJourneyRouteWithChildren
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/create/': typeof CreateIndexRoute
  '/create/journey/first-post': typeof CreateJourneyFirstPostRoute
  '/journey/$id/add': typeof JourneyIdAddRoute
  '/journey/$id/complete': typeof JourneyIdCompleteRoute
  '/journey/$id/posted': typeof JourneyIdPostedRoute
  '/journey/$id/settings': typeof JourneyIdSettingsRoute
  '/journey/$id/story': typeof JourneyIdStoryRoute
  '/create/journey/': typeof CreateJourneyIndexRoute
  '/journey/$id/': typeof JourneyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/profile'
    | '/reels'
    | '/create/journey'
    | '/journey/$id'
    | '/create/'
    | '/create/journey/first-post'
    | '/journey/$id/add'
    | '/journey/$id/complete'
    | '/journey/$id/posted'
    | '/journey/$id/settings'
    | '/journey/$id/story'
    | '/create/journey/'
    | '/journey/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/profile'
    | '/reels'
    | '/create'
    | '/create/journey/first-post'
    | '/journey/$id/add'
    | '/journey/$id/complete'
    | '/journey/$id/posted'
    | '/journey/$id/settings'
    | '/journey/$id/story'
    | '/create/journey'
    | '/journey/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/explore'
    | '/profile'
    | '/reels'
    | '/create/journey'
    | '/journey/$id'
    | '/create/'
    | '/create/journey/first-post'
    | '/journey/$id/add'
    | '/journey/$id/complete'
    | '/journey/$id/posted'
    | '/journey/$id/settings'
    | '/journey/$id/story'
    | '/create/journey/'
    | '/journey/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  JourneyIdRoute: typeof JourneyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/journey': {
      id: '/create/journey'
      path: '/journey'
      fullPath: '/create/journey'
      preLoaderRoute: typeof CreateJourneyRouteImport
      parentRoute: typeof CreateRoute
    }
    '/journey/$id/': {
      id: '/journey/$id/'
      path: '/'
      fullPath: '/journey/$id/'
      preLoaderRoute: typeof JourneyIdIndexRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/create/journey/': {
      id: '/create/journey/'
      path: '/'
      fullPath: '/create/journey/'
      preLoaderRoute: typeof CreateJourneyIndexRouteImport
      parentRoute: typeof CreateJourneyRoute
    }
    '/journey/$id/story': {
      id: '/journey/$id/story'
      path: '/story'
      fullPath: '/journey/$id/story'
      preLoaderRoute: typeof JourneyIdStoryRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/settings': {
      id: '/journey/$id/settings'
      path: '/settings'
      fullPath: '/journey/$id/settings'
      preLoaderRoute: typeof JourneyIdSettingsRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/posted': {
      id: '/journey/$id/posted'
      path: '/posted'
      fullPath: '/journey/$id/posted'
      preLoaderRoute: typeof JourneyIdPostedRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/complete': {
      id: '/journey/$id/complete'
      path: '/complete'
      fullPath: '/journey/$id/complete'
      preLoaderRoute: typeof JourneyIdCompleteRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/add': {
      id: '/journey/$id/add'
      path: '/add'
      fullPath: '/journey/$id/add'
      preLoaderRoute: typeof JourneyIdAddRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/create/journey/first-post': {
      id: '/create/journey/first-post'
      path: '/first-post'
      fullPath: '/create/journey/first-post'
      preLoaderRoute: typeof CreateJourneyFirstPostRouteImport
      parentRoute: typeof CreateJourneyRoute
    }
  }
}

interface CreateJourneyRouteChildren {
  CreateJourneyFirstPostRoute: typeof CreateJourneyFirstPostRoute
  CreateJourneyIndexRoute: typeof CreateJourneyIndexRoute
}

const CreateJourneyRouteChildren: CreateJourneyRouteChildren = {
  CreateJourneyFirstPostRoute: CreateJourneyFirstPostRoute,
  CreateJourneyIndexRoute: CreateJourneyIndexRoute,
}

const CreateJourneyRouteWithChildren = CreateJourneyRoute._addFileChildren(
  CreateJourneyRouteChildren,
)

interface CreateRouteChildren {
  CreateJourneyRoute: typeof CreateJourneyRouteWithChildren
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateJourneyRoute: CreateJourneyRouteWithChildren,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface JourneyIdRouteChildren {
  JourneyIdAddRoute: typeof JourneyIdAddRoute
  JourneyIdCompleteRoute: typeof JourneyIdCompleteRoute
  JourneyIdPostedRoute: typeof JourneyIdPostedRoute
  JourneyIdSettingsRoute: typeof JourneyIdSettingsRoute
  JourneyIdStoryRoute: typeof JourneyIdStoryRoute
  JourneyIdIndexRoute: typeof JourneyIdIndexRoute
}

const JourneyIdRouteChildren: JourneyIdRouteChildren = {
  JourneyIdAddRoute: JourneyIdAddRoute,
  JourneyIdCompleteRoute: JourneyIdCompleteRoute,
  JourneyIdPostedRoute: JourneyIdPostedRoute,
  JourneyIdSettingsRoute: JourneyIdSettingsRoute,
  JourneyIdStoryRoute: JourneyIdStoryRoute,
  JourneyIdIndexRoute: JourneyIdIndexRoute,
}

const JourneyIdRouteWithChildren = JourneyIdRoute._addFileChildren(
  JourneyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  JourneyIdRoute: JourneyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
